language: csharp

matrix:
  include:
    - dotnet: 2.1.3
      mono: none
      env: CONFIGURATION=Debug FRAMEWORK=netcoreapp2.1
    - dotnet: 2.1.3
      mono: none
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp2.1

before_script:
  - dotnet --info
  - dotnet restore

script:
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK tests/Spreads.Core.xUnit/Spreads.Core.xUnit.csproj