# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -c Release  --filter TestCategory=CI -v m
  displayName: 'Test Release'
- script: dotnet test tests/Spreads.Core.Tests/Spreads.Core.Tests.csproj -c Debug  --filter TestCategory=CI -v m
  displayName: 'Test Debug'